/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SelectExampleImport } from './routes/select-example'
import { Route as BasicExampleImport } from './routes/basic-example'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SelectExampleRoute = SelectExampleImport.update({
  id: '/select-example',
  path: '/select-example',
  getParentRoute: () => rootRoute,
} as any)

const BasicExampleRoute = BasicExampleImport.update({
  id: '/basic-example',
  path: '/basic-example',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/basic-example': {
      id: '/basic-example'
      path: '/basic-example'
      fullPath: '/basic-example'
      preLoaderRoute: typeof BasicExampleImport
      parentRoute: typeof rootRoute
    }
    '/select-example': {
      id: '/select-example'
      path: '/select-example'
      fullPath: '/select-example'
      preLoaderRoute: typeof SelectExampleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basic-example': typeof BasicExampleRoute
  '/select-example': typeof SelectExampleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basic-example': typeof BasicExampleRoute
  '/select-example': typeof SelectExampleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/basic-example': typeof BasicExampleRoute
  '/select-example': typeof SelectExampleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/basic-example' | '/select-example'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/basic-example' | '/select-example'
  id: '__root__' | '/' | '/basic-example' | '/select-example'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasicExampleRoute: typeof BasicExampleRoute
  SelectExampleRoute: typeof SelectExampleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasicExampleRoute: BasicExampleRoute,
  SelectExampleRoute: SelectExampleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/basic-example",
        "/select-example"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/basic-example": {
      "filePath": "basic-example.tsx"
    },
    "/select-example": {
      "filePath": "select-example.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
